#!/bin/bash
#PBS -l mem=62gb,nodes=1:ppn=24,walltime=48:00:00
#PBS -m abe
#PBS -M liux1299@umn.edu
#PBS -q small

set -e
set -o pipefail

module load R/3.4.3
module load python2/2.7.12_anaconda4.2 # Tom's VCF_To_Htable-TK.py script runs in Python 2
module load vcflib_ML/1.0.0
module load parallel

#   Usage message:
#   This script performs LD analysis on 100Kb windows around fst outlier SNPs from Environmental
#   Associations project fstOutlier analysis. This script pulls together all parts of the analysis
#   performed by multiple scripts.
#   Please fill out user provided argument fields and submit script as job.


#   User provided arguments
#   Where is the directory containing this script?
#   Make sure all scripts needed are in same directory as this script
SCRIPT_DIR=/home/morrellp/liux1299/GitHub/Env_Assoc/script/LD_Analysis
#   List of sorted fst oulier SNP names based on Ana's fstOutlier analysis
FST_OUTLIER_SNPS=/home/morrellp/liux1299/Projects/Land_Env_Assoc/Analysis/LD_Analysis/data/FstOutliers_uniq_ele_lati_gh_99th_sorted.txt
#   Need sorted_all_9k_masked_90idt.vcf
VCF_9K=/home/morrellp/liux1299/GitHub/9k_BOPA_SNP/BOPA_9k_vcf_Morex_refv1/sorted_all_9k_masked_90idt.vcf
#   VCF file from dataset we are interested in (i.e. OnlyLandrace_Barley_NAM_Parents_Final_renamed.vcf)
MAIN_VCF=/panfs/roc/groups/9/morrellp/shared/Projects/Land_Env_Assoc/Analysis/LD_Analysis/data/NAM_landraces_100_DP2_renamed_2018-05-21.vcf
#   window size (bp) upstream/downstream of SNP for extract_BED.R
BP=100000
#   Minor Allele Frequency threshold to use for VCF to Htable conversion (i.e. 0.01 for 1% MAF)
MAF=0.01
#   Missing data threshold to use for filtering (i.e. 0.15 for 15% missing data)
P_MISSING=0.20
#   What prefix do we want to use for our output files?
PREFIX=ld_Barley_NAM_200Kb_0.20
#   Where is our output directory?
OUT_DIR=/home/morrellp/liux1299/Shared/Projects/Land_Env_Assoc/Analysis/LD_Analysis/results/fst_outlier_snps_200Kb/0.20_threshold_99th

#   Pull functions from LD_analysis_fstOutliers.sh script
source "${SCRIPT_DIR}"/LD_analysis_fstOutliers.sh

#   Run anaylsis
main "${SCRIPT_DIR}" "${FST_OUTLIER_SNPS}" "${VCF_9K}" "${MAIN_VCF}" "${BP}" "${MAF}" "${P_MISSING}" "${PREFIX}" "${OUT_DIR}"
