#!/usr/bin/env bash

#PBS -l mem=22gb,nodes=1:ppn=16,walltime=24:00:00
#PBS -m abe
#PBS -M liux1299@umn.edu
#PBS -q lab

set -e
set -o pipefail

module load R/3.4.0

#   User provided paths
#   Genotype data frame that is sorted by SNP name
GENO=/home/morrellp/liux1299/Shared/Projects/Land_Env_Assoc/Analysis/LD_Analysis/results/Chr1_sorted_EXISTS.txt
#   SNP_BAC.txt file that has two columns called "Query_SNP" and "PhysPos"
PHYS_POS=/home/morrellp/liux1299/Shared/Projects/Land_Env_Assoc/Analysis/LD_Analysis/results/SNP_BAC_Chr1_filtered.txt
#   Heatmap plot name
PLOT_NAME="Chr 1 All Landrace"
#   Output file prefix
PREFIX=Chr1
#   Where do our output files go?
OUT_DIR=/home/morrellp/liux1299/Shared/Projects/Land_Env_Assoc/Analysis/LD_Analysis/results/Chr1_All
#   Valid options are: include or exclude
INCLUDE_SNP_NAME=exclude

/home/morrellp/liux1299/GitHub/Env_Assoc/script/LD_Analysis/LDheatmap_GBS.R "${GENO}" "${PHYS_POS}" "${PLOT_NAME}" "${PREFIX}" "${OUT_DIR}" "${INCLUDE_SNP_NAME}"
